### ISSUE TITLE
Mod unknown by VanillaFix causes issue

### ISSUE THREAD

**Issue by theJulesDude** [xJon/The-1.12.2-Pack#134]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log https://paste.dimdev.org/idalorikar.mccrash
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

I get constant warnings from VanillaFix and it doesn't know which mod throws the error. Additionally there are chunk errors and blocks aren't updated.
I play on a server I'm hosting and a friend who's also playing on the server gets apperently the same error from VanillaFix and also has chunk errors and incorrect blockupdates.
Also when starting the server there's an error message which is always the same:

```
[07:07:20 ERROR]: Exception handling console input
java.io.IOException: Handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:273) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:283) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:344) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:185) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:326) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:392) ~[?:?]
	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]
```

Please help

**Comment by xJon** [comment]
`java.util.concurrent.ExecutionException: java.lang.NullPointerException` crashes might be due to VanillaFix networking problems and can be ignored.
If you want help regarding your server log, please post all of it using a [paste-tool](http://paste.ubuntu.com/).
