### ISSUE TITLE
Which Java Version i need for Server?

### ISSUE THREAD

**Issue by corincorvus** [xJon/The-1.12.2-Pack#160]
Hi, 
i installed a fresh 1.0.3 Server of your Pack on my Linux Debian Buster Server.
It have Java 13.x.x

if i start the "LaunchServer.sh" i get an error:
./LaunchServer.sh
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java
.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of
 loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

Permissions are granted.
Any Idea, what is wrong?

**Comment by corincorvus** [comment]
Ah ok Java 8. Now it start.

**Comment by xJon** [comment]
👍
