### ISSUE TITLE
Crashing when players go to GC planets.

### ISSUE THREAD

**Issue by Zilacon** [xJon/The-1.12.2-Pack#446]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Im using Technic. Yes im on a Premium Account.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
32GB of ram.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes.

```
java.lang.ClassCastException: net.minecraft.world.biome.BiomePlains incompatible with micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive
	at com.mjr.extraplanets.planets.Saturn.worldgen.BiomeDecoratorSaturn.decorate(BiomeDecoratorSaturn.java:80)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:42)
	at com.mjr.extraplanets.planets.Saturn.worldgen.ChunkProviderSaturn.decoratePlanet(ChunkProviderSaturn.java:74)
	at com.mjr.mjrlegendslib.world.ChunkProviderMultiBiomeSpace.func_185931_b(ChunkProviderMultiBiomeSpace.java:288)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1167)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1127)
	at net.minecraft.world.gen.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:182)
	at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:154)
	at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:150)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:146)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:185)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:453)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
	at java.lang.Thread.run(Thread.java:821)
```

**Information required**
1. Is the modpack crashing: Yes
2. Crash/latest log https://pastebin.com/qDme5Ahf
3. Is Optifine installed or any other additional mods: No, its a server.

**Describe the issue**
Take rocket to a planet like saturn, server crashes whenever that player joins.
As far as i know this was never an issue on the previous version.

**Comment by xJon** [comment]
Hi, did you change any of the default Galacticraft or ExtraPlanets configs?

**Comment by Zilacon** [comment]
Nope, defaults.

**Comment by xJon** [comment]
Does this issue happen for you on singleplayer as well?

**Comment by Zilacon** [comment]
No seems to be fine on single player.

**Comment by xJon** [comment]
Then you must've done changes on your server; I cannot reproduce this on a clean server installation of the pack.
