### ISSUE TITLE
Can't process Aluminium Ore in IC2 Macerator

### ISSUE THREAD

**Issue by Luro02** [xJon/The-1.12.2-Pack#461]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
3. Is Optifine installed or any other additional mods: **yes** (Optifine)

**Describe the issue**

Galacticraft adds [`Aluminium Ore`](https://wiki.micdoodle8.com/wiki/Aluminum_Ore), but it cannot be crushed in a [`Macerator`](https://wiki.industrial-craft.net/index.php/Macerator). The Galacticraft wiki seems to suggest that this should work?

> Galacticraft 4 build 139 (February 2018) adds full Aluminum Ore compatibility with the IndustrialCraft 2 Macerator and also the Applied Energistics 2 Quartz Grindstone, Actually Additions Crusher, and EnderIO SAG Mill. So there is Aluminum Dust and (if IC2 is present) also Crushed Aluminum Ore and Purified Crushed Aluminum Ore.
>
> If processed fully through three stages of IC2's ore processing machines, 1 x Aluminum Ore yields the following:
>
> - 2 x Aluminum Dust
> - 2 x Tiny Pile of Iron Dust
> - 1 x Tiny Pile of Titanium Dust
> - 1 x Stone Dust

https://wiki.micdoodle8.com/wiki/Aluminum_Ore

**Comment by xJon** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/8945347/85943029-0e72d280-b936-11ea-9638-c9552049b8df.png)

What version of the modpack are you using?

**Comment by Luro02** [comment]
Hmmm, strange. I am using `v.1.2.0`.

I searched through the log file and found the following lines that might be relevant:

```
[11:38:21] [Client thread/ERROR]: Could not load override model thermalfoundation:item/tool/fishing_rod_aluminum_cast for model thermalfoundation:models/item/tool/fishing_rod_aluminum
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: circular model dependencies, stack: [thermalfoundation:item/tool/fishing_rod_aluminum_cast]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:108) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModelOrLogError(ModelLoaderRegistry.java:211) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.getDependencies(ModelLoader.java:364) [ModelLoader$VanillaModelWrapper.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:182) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModelOrLogError(ModelLoaderRegistry.java:211) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.getTextures(ModelLoader.java:387) [ModelLoader$VanillaModelWrapper.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:171) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModelOrLogError(ModelLoaderRegistry.java:211) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.getDependencies(ModelLoader.java:364) [ModelLoader$VanillaModelWrapper.class:?]
	at team.chisel.ctm.client.util.TextureMetadataHandler.onModelBake(TextureMetadataHandler.java:149) [TextureMetadataHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1101_TextureMetadataHandler_onModelBake_ModelBakeEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:414) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:30) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:513) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3931) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:39:07] [Client thread/ERROR]: Cannot add smelting recipe Smelting: Aluminium Dust (1xitem.ic2compat@0 => 1xitem.thermalfoundation.material@132) because another mod already has registered a recipe 1xitem.ic2compat@0 => 1xitem.basic_item@5.
[11:39:07] [Client thread/ERROR]: Cannot add smelting recipe Smelting: Aluminum Dust (1xitem.ic2compat@0 => 1xitem.thermalfoundation.material@132) because another mod already has registered a recipe 1xitem.ic2compat@0 => 1xitem.basic_item@5.
```
