### ISSUE TITLE
Server Crash from Fluid transfer. 

### ISSUE THREAD

**Issue by AdorableKitteh** [xJon/The-1.12.2-Pack#62]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Is the modpack crashing: **yes / no** yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Describe the issue**
Server crashed From placing a normal water bottle with water into the fluid transferer machine block. removing water from the bottle.
---- Minecraft Crash Report ----
// My bad.

Time: 2019-12-15 16:29:59 AEDT
Description: Ticking block entity

kotlin.KotlinNullPointerException
    at net.ndrei.teslacorelib.utils.FluidUtils.fillFluidFrom(FluidUtils.kt:60)
    at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:16)
    at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:22)
    at net.ndrei.teslacorelib.utils.FluidextensionsKt.processInputInventory(fluidextensions.kt:27)
    at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processFluidItems(SidedTileEntity.kt:544)
    at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processImmediateInventories(SidedTileEntity.kt:214)
    at net.ndrei.teslacorelib.tileentities.ElectricMachine.processImmediateInventories(ElectricMachine.kt:298)
[crash-2019-12-15_16.29.59-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/3964650/crash-2019-12-15_16.29.59-server.txt)

    at net.ndrei.teslacorelib.tileentities.SidedTileEntity.update(SidedTileEntity.kt:992)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbd000(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
 

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
This seems to be related to https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/issues/28 which was apparently fixed, but never released.
Do you have any work around this crash?

**Comment by AdorableKitteh** [comment]
not really it destroyed the hole server.

**Comment by xJon** [comment]
You can restore a server backup for now.
> Restoring on a server: To restore a backup on a server use the server restore command like this: `/bm serverrestore <backup>`
Backup can be a date (The same date shown by `/bm listbackups`) or a number. If it's a number then the nth backup with be used. This command will restore the backup to a directory called restored_world. After it's finished restoring, replace the normal world directory with restored_world (e.g. if your world is called "world" (the default world name for servers) the delete world and rename restored_world to world)

**Comment by xJon** [comment]
This issue will be fixed when the mod author updates their mod. As this is not in my control, this issue will be closed for now.
