### ISSUE TITLE
All clients freeze when a player places a torch where a lever is, or opens a machine with a torch

### ISSUE THREAD

**Issue by SkyeOfBreeze** [xJon/The-1.12.2-Pack#732]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/NbGjAMzU (server log: Only took the last of it, as the log is too big for pastebin)
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Both clients are running 16GB of ram. One has 6GB allocated, and the other has 8GB allocated, but only one connected client is enough to show this issue.

Server world download for minimum method to reproduce (world only, no server config files. Those were not modified): https://www.dropbox.com/s/a3ygzvxo8q1lxof/forge_1_12_2_1456997.zip?dl=0

installed from: https://the-1122-pack.com/repo (1.3.7)

So the crash that is happening involves opening a macerator with a torch (the ones that have a lever just above them)
![image](https://user-images.githubusercontent.com/4467863/137660902-a0e59267-53e8-4626-bf6e-e80f8bf34c2c.png)
Video of freeze: https://youtu.be/ktlQhNl5s2U

The server throws:
```
[20:59:54] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: 0
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_292]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IndexOutOfBoundsException: 0
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:51) ~[scala-library-2.11.1.jar:?]
        at scala.collection.immutable.List.apply(List.scala:83) ~[List.class:?]
        at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:82) ~[MultipartGenerator$.class:?]
        at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:723) ~[TileMultipart$.class:?]
        at codechicken.multipart.ItemPlacementHelper$.place(ItemPlacementHelper.scala:57) ~[ItemPlacementHelper$.class:?]
        at codechicken.multipart.handler.MultipartSPH$.handlePacket(packethandlers.scala:92) ~[MultipartSPH$.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:135) ~[PacketCustom$ServerInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.lambda$handle$0(PacketCustom.java:133) ~[PacketCustom$ServerInboundHandler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
```

Usually followed by every connected minecraft client freezing (2 at the time), and requiring a restart of the clients. 

So the crash here is most reproduceable using a machine with lever above, but sometimes freezes when placing a switch on the ground with a lever on a wall (causes a collision issue where one or the other can only be there). 

This was reproduced on 2 separate machines running the same minecraft world, and a empty new world (supplied). One was a local ethernet to ethernet connection, and the other one was hosted online through a third party hosting server.

Edit: ProjectE was used in the main server, but was not used in the demo server to try to reproduce the issue using stock 1.12.2 mods

**Comment by xJon** [comment]
Can you reproduce the issue on singleplayer?

https://user-images.githubusercontent.com/8945347/137793207-5d90c13c-d6ba-4cec-af60-9f414018e407.mp4
