### ISSUE TITLE
Duped Voxelmap modfile on GDlauncher

### ISSUE THREAD

**Issue by Nicknaam70** [xJon/The-1.12.2-Pack#756]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

[14:26:43] [Client thread/FATAL]: Found a duplicate mod voxelmap at [C:\Users\nickn\AppData\Roaming\gdlauncher_next\instances\The 1 12 2 Pack  Perfectly Complex\..\..\instances\The 1 12 2 Pack  Perfectly Complex\mods\forgemod_VoxelMap-1.9.28_for_1.12.2.jar, ..\..\instances\The 1 12 2 Pack  Perfectly Complex\mods\forgemod_VoxelMap-1.9.28_for_1.12.2.jar]
[14:26:43] [Client thread/ERROR]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.DuplicateModsFoundException: 
Duplicate Mods:
	voxelmap : C:\Users\nickn\AppData\Roaming\gdlauncher_next\instances\The 1 12 2 Pack  Perfectly Complex\..\..\instances\The 1 12 2 Pack  Perfectly Complex\mods\forgemod_VoxelMap-1.9.28_for_1.12.2.jar
	voxelmap : C:\Users\nickn\AppData\Roaming\gdlauncher_next\instances\The 1 12 2 Pack  Perfectly Complex\..\..\instances\The 1 12 2 Pack  Perfectly Complex\mods\forgemod_VoxelMap-1.9.28_for_1.12.2.jar

	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:466) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:428) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3931) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Description of what help is needed.
the game sasys there are duped files but there is only one file of forge.voxelmap or is the 2th caled different?

**Comment by xJon** [comment]
I'm not sure what's causing this actually, you might be able to get support directly from the GDLauncher team regarding this, The 1.12.2 Pack is officially distributed only through the Technic & CurseForge launchers.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
