### ISSUE TITLE
1.4.0 Server Startup

### ISSUE THREAD

**Issue by burstfire9** [xJon/The-1.12.2-Pack#763]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: no

**Issue description**
Can't start the server with "LaunchServer.bat" I haven't edited anything and only extracted it to its own folder. When I run it normally it gives: "A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more"

error and when I run it in administrative mode: "Error: Unable to access jarfile forge-1.12.2-14.23.5.2860.jar" yes all the names are correct for the targeting of the bat file. Not sure why its upset. Any recommendations?

**Comment by xJon** [comment]
> Hi, you need to make sure you have Java SE 8 64-bit installed on your computer :)
You can find it through [here](https://www.java.com/en/download/manual.jsp).
Also, if you don't need the Java Development Kit version you currently have installed, you should remove it to avoid conflicts.
