### ISSUE TITLE
Teleporting while Morphing

### ISSUE THREAD

**Issue by PancakeCZ** [xJon/The-1.12.2-Pack#793]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Hey, I was Morphing into a blaze while teleporting to nether and my game crashed. Now when I want to join server my game keeps crashing even if I restart it. I am stucked somewhere between Nether and World and I can't do nothing. Any ideas?

**Comment by xJon** [comment]
Hi, you can try to restore a world backup! Also, you can include the crash log for more help :)

**Comment by OpenSauce04** [comment]
Bump, I also had this issue happen just earlier

**Comment by OpenSauce04** [comment]
```
[11:48:27] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.client.event.RenderHandEvent@7b1c5e77:
java.lang.NullPointerException: null
	at net.minecraft.client.model.ModelBiped.setRotationAngles(SourceFile:123) ~[bpx.class:?]
	at net.minecraft.client.model.ModelPlayer.setRotationAngles(SourceFile:117) ~[bqj.class:?]
	at me.ichun.mods.morph.client.render.RenderPlayerHand.renderRightArm(RenderPlayerHand.java:106) ~[RenderPlayerHand.class:?]
	at net.minecraft.client.renderer.ItemRenderer.renderArmFirstPerson(ItemRenderer.java:255) ~[buu.class:?]
	at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:358) ~[buu.class:?]
	at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:333) ~[buu.class:?]
	at me.ichun.mods.morph.client.core.EventHandlerClient.onRenderHand(EventHandlerClient.java:797) ~[EventHandlerClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2461_EventHandlerClient_onRenderHand_RenderHandEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:201) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:772) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1439) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
This appears to be an issue related to rendering the player's hand, likely due to the animation that plays while morphing being interrupted

**Comment by xJon** [comment]
@OpenSauce04 Not sure if there's much we can do about it unfortunately! Ideally reporting it directly to the mod author would be the best: https://github.com/iChun/Morph/issues

**Comment by OpenSauce04** [comment]
Alright, I've sent my log that way. I'd mark this as don't blame the modpack

**Comment by xJon** [comment]
As Morph is no longer in active development  for 1.12, I will mark this as `wontfix` for now but thank you nonetheless for the report!
