### ISSUE TITLE
Start Server Batch file error

### ISSUE THREAD

**Issue by LFU-07** [xJon/The-1.12.2-Pack#812]
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

Alright So I'm trying to run a server with my friends but I'm having trouble even starting up the server as every time I run the batch file I get this error, I'm completely at a loss and not sure what to do and some assistance would be greatly appreciated!

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more

**Comment by xJon** [comment]
Hi, you need to make sure you have Java SE 8 64-bit installed on your computer :)
You can find it through [here](https://www.java.com/en/download/manual.jsp).

**Comment by LFU-07** [comment]
See that's what I thought the problem was as well but I have it installed and even after uninstalling and reinstalling it still pops up with the same error, I can run normal Server jars but cant run the Forge so I'm at a complete loss.

**Comment by xJon** [comment]
You can head either to our Discord or Technic's and get help with launching the server :)
https://discord.com/invite/technic
https://discord.com/invite/jkDvz3Q

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested)!
