### ISSUE TITLE
Game Crash-Unable to reload (triggered on railcraft Steam engine (primed) having Mechanism Power Conector applied)

### ISSUE THREAD

**Issue by L-Aronia** [xJon/The-1.12.2-Pack#856]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes**.

**Information required**
1. Is the modpack crashing: **yes 
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
https://mclo.gs/Txrjhwr
3. Is Optifine installed or any other additional mods: **) / no**

**Describe the issue**

trying to power railcraft rock breaker just got it to work using 2x2 converter for the game, possible odd graphics, went back to other side of machine where railcraft steam engine, Commercial i believe, was primed with steam, disconected steam pipe (mekanism 4000mb) and attempted to put 2 stage mekanism power conduit on top to draw power from railcraft steam engine... immediately caused crash. (part of report below believe pipe error is mekanism power conduit)

<html>
<body>

java.lang.NullPointerException
--
9 | at mekanism.common.tile.transmitter.TileEntitySidedPipe.canConnectMutual(TileEntitySidedPipe.java:265)
10 | at mekanism.common.tile.transmitter.TileEntitySidedPipe.getPossibleTransmitterConnections(TileEntitySidedPipe.java:132)
11 | at mekanism.common.tile.transmitter.TileEntitySidedPipe.onLoad(TileEntitySidedPipe.java:487)
12 | at net.minecraft.world.World.addTileEntity(World.java:1924)
13 | at net.minecraft.world.World.addTileEntities(World.java:1951)
14 | at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:856)
15 | at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
16 | at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
17 | at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
18 | at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89)
19 | at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135)
20 | at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:344)
21 | at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:142)
22 | at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156)
23 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
24 | at java.lang.Thread.run(Thread.java:745)

</body>
</html>

java.lang.NullPointerException
    at mekanism.common.tile.transmitter.TileEntitySidedPipe.canConnectMutual(TileEntitySidedPipe.java:265)
    at mekanism.common.tile.transmitter.TileEntitySidedPipe.getPossibleTransmitterConnections(TileEntitySidedPipe.java:132)
    at mekanism.common.tile.transmitter.TileEntitySidedPipe.onLoad(TileEntitySidedPipe.java:487)
    at net.minecraft.world.World.addTileEntity(World.java:1[9](https://mclo.gs/Txrjhwr#L9)24)
    at net.minecraft.world.World.addTileEntities(World.java:1951)
    at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:856)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:[10](https://mclo.gs/Txrjhwr#L10)9)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:[11](https://mclo.gs/Txrjhwr#L11)8)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:[13](https://mclo.gs/Txrjhwr#L13)5)
    at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:344)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:[14](https://mclo.gs/Txrjhwr#L14)2)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:[15](https://mclo.gs/Txrjhwr#L15)6)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)

**Comment by xJon** [comment]
Any chance you can report this over https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/issues ?

**Comment by xJon** [comment]
Will close for now as this is a mod issue which is not under active development, but thank you for reporting nevertheless!
